spring:
  datasource:
    url:  jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:books}?useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Spectrum@2023}
    driverClassName:  com.mysql.cj.jdbc.Driver

  jpa:
#    database-platform:  org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
