server:
  port: 8080

spring:
  datasource:
    url:  jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Spectrum@2023
    driverClassName:  com.mysql.cj.jdbc.Driver
  jpa:
    # database-platform:  org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    compatibility-verifier:
      enabled:  false
# eureka:
#   instance:
#     prefer-ip-address:  true
#   client:
#     fetch-registry:  true
#     register-with-eureka: true
#     service-url:
#       defaultZone:  http://localhost:8761/eureka
