server:
  port: 8081

spring:
  datasource:
    url:  jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: Spectrum@2023
    driverClassName:  com.mysql.cj.jdbc.Driver
  jpa:
    # database-platform:  org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    compatibility-verifier:
      enabled:  false
